
#ifndef GB_EEPROMStrings_h
#define GB_EEPROMStrings_h

// Auto generated by ../GrowboxStringsLoader/GrowboxStringsLoader.ino do not edit directly

#include <EEPROM.h>

const word ES_printSendPinsStatus_PinOutputInput            = 0x0; // Pin OUTPUT INPUT
const word ES_printSendPinsStatus_OUTPUTOffset             = 0x11; //      -   
const word ES_printSendPinsStatus_INPUTOffset              = 0x1B; //   -     
const word ES_printSendPinsStatus_ReservedBySerialUSB      = 0x24; // Reserved by Serial/USB. Can be used, if Serial/USB won't be connected
const word ES_printSendPinsStatus_RelayLight               = 0x6A; // Relay: light on(0)/off(1)
const word ES_printSendPinsStatus_RelayFan                 = 0x84; // Relay: fan max(0)/min(1) speed switch
const word ES_printSendPinsStatus_RelayFanMinMax           = 0xAA; // Relay: fun max(0)/min(1) speed switch
const word ES_printSendPinsStatus_1Wire                    = 0xD0; // 1-Wire: termometer
const word ES_printSendPinsStatus_SerialMonotor            = 0xE3; // Use serial monitor on(1)/off(0)
const word ES_printSendPinsStatus_ErrorStatus             = 0x103; // Error status
const word ES_printSendPinsStatus_Breeze                  = 0x110; // Breeze
const word ES_printSendPinsStatus_I2C                     = 0x117; // Reserved by I2C. Can be used, if SCL, SDA pins will be used

static String EEPROMStringLoad(word offset) {
  String rez;
  char c = EEPROM.read(offset++);
   while(c){
    rez += c;
    c = EEPROM.read(offset++);
  }
  return rez;
}
#endif

